name: Deploy Flutter Web (WASM) to GitHub Pages

on:
  push:
    tags:
      - '*'  # Trigger on any tag push

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.1'
          channel: stable

      - name: Show Flutter version
        run: flutter --version

      - name: Clean old builds
        run: flutter clean

      - name: Get dependencies
        run: flutter pub get

      - name: Build Flutter Web (WASM)
        run: flutter build web --wasm --release --base-href=/portfolio/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GH_PAT }}
          publish_dir: ./build/web
          force_orphan: true